### ISSUE TITLE
Question: recursive variants

### ISSUE THREAD

**Issue by sigma-andex** [natefaubion/purescript-heterogeneous#12]
For my data transformation library I needed variants of map and sequence record that not only work on the first level of a record but recurse the record in case it is a nested record. For that I created three functions:
- [hsequenceRec](https://github.com/sigma-andex/purescript-morello/blob/v0.1.1/src/Morello/Morello/Record.purs#L73) ([example](https://github.com/sigma-andex/purescript-morello/blob/v0.1.1/test/Morello/Morello/RecordSpec.purs#L32-L58)) - sequence recursively the whole record
- [hmapRec](https://github.com/sigma-andex/purescript-morello/blob/v0.1.1/src/Morello/Morello/Record.purs#L144) ([example](https://github.com/sigma-andex/purescript-morello/blob/v0.1.1/test/Morello/Morello/RecordSpec.purs#L74-L103)) - map a function recursively over the whole record
- [hmapKRec](https://github.com/sigma-andex/purescript-morello/blob/v0.1.1/src/Morello/Morello/Record.purs#L215) ([example](https://github.com/sigma-andex/purescript-morello/blob/v0.1.1/test/Morello/Morello/RecordSpec.purs#L104-L133)) - map a natural transformation recursively over the whole record

I think these functions could be useful for others as well. Would you see that as something to be added to this library, e.g. in a submodule? If so I could create a PR for it. Or do you think it's better to create another library for these things?

**Comment by natefaubion** [comment]
It's my policy for this particular library that I'm not trying to maintain a utility belt, only the abstractions that make it work. There's about a million ways you can slice a record 😆. I think it would be appropriate to put things like this in an `extras` library.

**Comment by sigma-andex** [comment]
Ok makes sense. Will do this then. Thx!
